from typing import Union

uint8 = int
uint16 = int
uint24 = int
uint32 = int
uint40 = int
uint48 = int
uint56 = int
uint64 = int
uint72 = int
uint80 = int
uint88 = int
uint96 = int
uint104 = int
uint112 = int
uint120 = int
uint128 = int
uint136 = int
uint144 = int
uint152 = int
uint160 = int
uint168 = int
uint176 = int
uint184 = int
uint192 = int
uint200 = int
uint208 = int
uint216 = int
uint224 = int
uint232 = int
uint240 = int
uint248 = int
uint256 = int

bytes1 = Union[bytearray, bytes]
bytes2 = Union[bytearray, bytes]
bytes3 = Union[bytearray, bytes]
bytes4 = Union[bytearray, bytes]
bytes5 = Union[bytearray, bytes]
bytes6 = Union[bytearray, bytes]
bytes7 = Union[bytearray, bytes]
bytes8 = Union[bytearray, bytes]
bytes9 = Union[bytearray, bytes]
bytes10 = Union[bytearray, bytes]
bytes11 = Union[bytearray, bytes]
bytes12 = Union[bytearray, bytes]
bytes13 = Union[bytearray, bytes]
bytes14 = Union[bytearray, bytes]
bytes15 = Union[bytearray, bytes]
bytes16 = Union[bytearray, bytes]
bytes17 = Union[bytearray, bytes]
bytes18 = Union[bytearray, bytes]
bytes19 = Union[bytearray, bytes]
bytes20 = Union[bytearray, bytes]
bytes21 = Union[bytearray, bytes]
bytes22 = Union[bytearray, bytes]
bytes23 = Union[bytearray, bytes]
bytes24 = Union[bytearray, bytes]
bytes25 = Union[bytearray, bytes]
bytes26 = Union[bytearray, bytes]
bytes27 = Union[bytearray, bytes]
bytes28 = Union[bytearray, bytes]
bytes29 = Union[bytearray, bytes]
bytes30 = Union[bytearray, bytes]
bytes31 = Union[bytearray, bytes]
bytes32 = Union[bytearray, bytes]
