#!/usr/bin/env bash

ZERO=0;

echo "/woke/.githooks/pre-commit executing..."

function check_last_command()
{
    if [ $? -gt $ZERO ];
    then
        exit 1;
    fi
}

# TODO: Fix black & pyright pre-commit hooks
#  There are two problems with our current pre-commit hooks:
#    1. `black` and `pyright` run also on files that are not being committed.
#    2. we don't immediately commit the changes that `black` makes
#  Ideally, we'll fix this soon.
#  assignees: michprev
echo "running \`black woke\`"
black woke;
check_last_command;
echo "running \`pytest woke\`"
pytest woke;
check_last_command;
echo "running \`pyright woke/woke\`"
pyright woke/woke;
check_last_command;

echo "/woke/.githooks/pre-commit successfully executed."