#!/usr/bin/env bash

ZERO=0;

echo "/woke/.githooks/pre-commit executing..."

function check_last_command()
{
    if [ $? -gt $ZERO ];
    then
        exit 1;
    fi
}

touch woke/.post-commit-ignore

# commit staged changes so that they are not included into stash
git commit --no-verify -m 'pre-commit hook tmp commit'
# stash unstaged changes
git stash
# restore staged changes
git reset --soft 'HEAD^'

rm woke/.post-commit-ignore

pyfiles=()
IFS=$'\n'
for f in $(git diff --cached --name-only --diff-filter=ACMR)
do
    if [[ "$f" == *.py ]]; then
        pyfiles+=("$f")
    fi
done

if [ ${#pyfiles[@]} -ne 0 ]; then
    echo "running \`black ${pyfiles[@]}\`"
    black woke;
    check_last_command;
fi

echo "running \`pytest woke\`"
pytest woke;
check_last_command;

if [ ${#pyfiles[@]} -ne 0 ]; then
    echo "running \`pyright ${pyfiles[@]}\`"
    pyright "${pyfiles[@]}";
    check_last_command;
fi

echo "/woke/.githooks/pre-commit successfully executed."