site_name: Woke

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top

nav:
  - Woke: 'index.md'
  - Contributing: 'contributing.md'
  - API reference:
    - api_reference/index.md
    - a_config: api_reference/a_config.md

plugins:
- search
- mkdocstrings:
    watch:
      - woke
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
          - https://networkx.org/documentation/stable/objects.inv
- mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
