[tool.black]
target-version = ["py37"]

[tool.pyright]
strict = "**/*.py"

[tool.portray]

[tool.pytest.ini_options]
markers = [
    "platform_dependent: platform-dependent test that will need to run on all CIs",
    "slow: slow tests that will not run in git hooks",
]
