name: Test Build

on:
  push:
    branches:
      - "feat/version-5.0.0"
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Add x86 Rust target on macOS
      if: runner.os == 'macOS'
      run: |
        rustup target add x86_64-apple-darwin

    - name: Update Rust
      if: runner.os != 'Linux'
      run: |
        rustup update stable && rustup default stable

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel

    # Build the entire package with wake_rs using cibuildwheel
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_SKIP: cp36-* cp37-* pp* *-musllinux_i686
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_ARCHS_LINUX: auto aarch64
        CIBW_BEFORE_ALL_WINDOWS: rustup target add i686-pc-windows-msvc
        CIBW_BEFORE_ALL_LINUX: |
          yum install -y openssl-devel libatomic || apt install -y pkg-config libssl-dev libatomic1 || apk add --no-cache openssl-dev
          curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=stable --profile=minimal -y
        CIBW_REPAIR_WHEEL_COMMAND_MACOS: |
          if [ "$(uname -m)" = "x86_64" ]; then
              export MACOSX_DEPLOYMENT_TARGET=10.12
          else
              export MACOSX_DEPLOYMENT_TARGET=14.0
          fi
          delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}
        CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}
        path: wheelhouse/*.whl
